### ISSUE TITLE
Create example directory

### ISSUE THREAD

**Issue by vhc102** [pys-info/pys-issue-tracker#2]
- create example project where user can download and run it directly. Add some static settings.

**Comment by rumitpysquad** [comment]
**TODO:** need to configure the package in the example app once we have successfully deployed the package in pypy.

**Comment by pys-info** [comment]
> 

No problem @rumitpysquad For now we just clone and test. I will assign tester in some time

**Comment by pys-info** [comment]
test

**Comment by pys-info** [comment]
test

**Comment by rumitpysquad** [comment]
@pys-info From my end, development is completed. I'm closing this issue for now.
