### ISSUE TITLE
Add basic test cases

### ISSUE THREAD

**Issue by vhc102** [pys-info/pys-issue-tracker#3]
- add some basic test cases which will raise the issue and  we can notify via different channels
- Also please add test coverage result as well

**Comment by rumitpysquad** [comment]
**PR**:    [https://github.com/pys-info/pys-issue-tracker/pull/6]

**Coverage Report For the test cases:**

![image](https://github.com/pys-info/pys-issue-tracker/assets/132981084/8c9f3451-33d0-49a8-b97d-b7a20c4fcf25)

**Comment by rumitpysquad** [comment]
@pys-info I'm closing this issue for now.

**Comment by vhc102** [comment]
@rumitpysquad can you please add tests for
